# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory (28 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional

license="GNU Lesser General Public License v3.0"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="ars_spell_book_curio" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ars Spell Book Curio" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Hathfury" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds a curio slot for spell books and allows quick casting from that book.
'''

[[dependencies.ars_spell_book_curio]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ars_spell_book_curio]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.1-61,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ars_spell_book_curio]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.1-5.0.3.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ars_spell_book_curio]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[2.5.0,)"
    ordering="AFTER"
    side="BOTH"